config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get '/about' => 'homes#about'
  get '/favorites/:id' => 'posts#favorite', as: 'favorite'

  resources :books, only: [:show, :create] do
    collection do
      get :search
    end
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      get :unsubscribe
      patch :withdraw
    end
  end
end

app/models/admin_book.rb
class AdminBook < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :book
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :admin_books
  has_many :users, through: :admin_books
  has_many :posts
  validates :title, :author, :isbn, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :admin_books, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :reason, presence: true
  validates :star, :comment, presence: true, on: :update
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum gender: { 男性: 0, 女性: 1 }

  validates :name, :birthday, :gender, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :admin_books, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :books, through: :admin_books
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:about, :top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [:name, :birthday, :gender, :email]
    )
    devise_parameter_sanitizer.permit(
      :update, keys: [:name, :birthday, :gender, :email, :profile_image, :password]
    )
  end

  private

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def search
    @keyword = params[:keyword]
    @model = params[:model]
    # 楽天ブックスの検索結果を@resultsに格納
    if @keyword.present? && @model == "title"
      @results = RakutenWebService::Books::Book.search(title: @keyword)
    elsif @keyword.present? && @model == "author"
      @results = RakutenWebService::Books::Book.search(author: @keyword)
    else
      flash[:danger] = "キーワードを入力してください。"
      redirect_to user_path(current_user)
    end
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    book_entry = Book.find_by(isbn: @book.isbn)
    if book_entry.present?
      redirect_to new_post_path(book: book_entry)
    else
      @book.save
      redirect_to new_post_path(book: @book)
    end
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :author, :isbn, :publication_date, :book_image_id, :book_image_large_id, :item_url
    )
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def index
    @book = Book.find_by(isbn: params[:isbn])
    @posts = Post.where(book_id: @book.id)
  end

  def new
    @book = Book.find(params[:book])
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.reason = params[:reason]
    @post.user_id = current_user.id
    # 投稿時、admin_bookも同時に生成
    if @post.save
      admin_book = @post.admin_books.build(
        user_id: current_user.id, book_id: @post.book_id, want_read: true
      )
      admin_book.save
      redirect_to post_path(@post)
    else
      @book = @post.book
      @post = Post.new
      flash.now[:danger] = '入力は必須です'
      render 'new'
    end
  end

  def edit
    @book = @post.book
  end

  # 読みたい本→読んだ本にadmin_bookを変更
  def update
    @post = Post.find(params[:id])
    # Cloud Natural Language APIを有効にする
    # @post.score = Language.get_data(post_params[:comment])
    if @post.update(post_params)
      @post.admin_books.update(have_read: true)
      redirect_to post_path(@post)
    else
      @book = @post.book
      flash.now[:danger] = '評価とコメントを入力してください'
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def favorite
    @user = User.find(params[:id])
    @favorites = Favorite.where(user_id: params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    # 投稿削除時、userのadmin_bookも同時に削除
    if post.destroy
      post.admin_books.destroy_all
      flash[:success] = '投稿を削除しました'
      redirect_to user_path(current_user)
    end
  end

  private

  def post_params
    params.require(:post).permit(:book_id, :reason, :star, :comment)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :unsubscribe]

  def show
    @user = User.find(params[:id])
    want_reads_array = []
    have_reads_array = []
    @want_reads = []
    @have_reads = []
    # want_readsに読みたい本、have_readsに読んだ本の情報をそれぞれ格納
    @user.admin_books.order(updated_at: :desc).each do |admin_book|
      if admin_book.want_read == true && admin_book.have_read == false
        want_reads_array << admin_book
        @want_reads = Kaminari.paginate_array(want_reads_array).page(params[:page]).per(5)
      elsif admin_book.want_read == true && admin_book.have_read == true
        have_reads_array << admin_book
        @have_reads = Kaminari.paginate_array(have_reads_array).page(params[:page]).per(5)
      end
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def unsubscribe
  end

  def withdraw
    @user = current_user
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :birthday, :gender, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # isbnからbookの特定
  def book_search(book_isbn)
    Book.find_by(isbn: book_isbn)
  end

  # 読んだ人数をisbnでカウントする
  def read_people(book_isbn)
    AdminBook.where(book_id: book_search(book_isbn), have_read: true).count
  end

  # ページタイトルの設定（指定なしならForWhat?）
  def full_title(page_title)
    base_title = "For What?"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_show.html.erb
<div class="book-info text-center"><i class="fas fa-book-open"></i>  Book Information</div>
<div class="book-info__content">
  <p class="book-info__image"><%= image_tag(book.book_image_large_id) %></p>
  <div class="book-info__text">
    <p class="book-info__title"><%= link_to book.title,book.item_url %></p>
    <p class="book-info__author"><%= book.author %></p>
    <p class="book-info__date">発売日：<%= book.publication_date %></p>
  </div>
</div>

app/views/books/search.html.erb
<% provide(:title, "検索結果") %>
<div class="row">
  
  <div class="col-md-3">
    <%= render 'users/profile', user: current_user %>
  </div>
  
  <div class="col-md-9">
    <h2>検索結果</h2>
    <% if @results.present? %>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>著者名</th>
            <th>出版社</th>
            <th>人数</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |result| %>
          <tr>
            <td><%= link_to image_tag(result.small_image_url),result.item_url %></td>
            <td><%= link_to result.title,result.item_url %></td>
            <td><%= result.author %></td>
            <td><%= result.publisher_name %></td>
            <td>
              <% if read_people(result.isbn) == 0 %>
                0人
              <% else %>
                <%= link_to read_people(result.isbn), posts_path(isbn: result.isbn) %>人
              <% end %>
            </td>
            <td>
              <!--current_userのAdminBookに、該当bookの登録がなければ、bookのcreateへbook情報を送る-->
              <% if AdminBook.where(user_id: current_user.id, book_id: book_search(result.isbn)).empty? %>
                <%= form_with model: @book, url: books_path, local: true do |f| %>
                  <%= f.hidden_field :title, :value => result.title %>
                  <%= f.hidden_field :author, :value => result.author %>
                  <%= f.hidden_field :isbn, :value => result.isbn %>
                  <%= f.hidden_field :publication_date, :value => result.sales_date %>
                  <%= f.hidden_field :book_image_id, :value => result.small_image_url %>
                  <%= f.hidden_field :book_image_large_id, :value => result.large_image_url %>
                  <%= f.hidden_field :item_url, :value => result.item_url %>
                  <%= f.submit "読みたい本登録", class: 'btn btn-link' %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if post.star != nil && post.favorited_by?(current_user) %>
  <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= post.favorites.count %> いいね
  <% end %>
<% elsif post.star != nil %>
  <%= link_to post_favorites_path(post), method: :post, remote: true do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= post.favorites.count %> いいね
  <% end %>
<% else %>
<% end %>

app/views/favorites/create.js.erb
$("#post_<%= @post.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', post: @post) %>");
$("#post_<%= @post.id %> .favorite-count").html("<%= j(render 'users/profile', user: @post.user) %>");

app/views/favorites/destroy.js.erb
$("#post_<%= @post.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', post: @post) %>");
$("#post_<%= @post.id %> .favorite-count").html("<%= j(render 'users/profile', user: @post.user) %>");

app/views/homes/about.html.erb
<% provide(:title, "About") %>
<div class="row">
  <div class="col-mx-8 col-md-offset-8 center-block about">
    <h2>For What?とは</h2>
    <h4 class="about__text">
      For What?は読書記録を管理し、感想を投稿するSNSです。<br>
      ユーザーは、本を読んだ目的や背景と、その評価を投稿します。<br>
      他のユーザがどんな目的で読み、どういった評価をしているかを知ることで、
      本とのミスマッチを防ぎます。
    </h4>
    <h2>本を読んだ目的と評価を投稿</h2>
      <div class="about__contents">
        <div class="about__parts">
          <p class="about__p">目的や背景と一緒に、読みたい本を登録する</p>
          <%= image_tag "want-read.png", :width => '80%', :class => 'about__image'  %>
          <p class="about__p">読み終えたら評価をして、読んだ本に登録する</p>
          <%= image_tag "have-read.png", :width => '80%', :class => 'about__image'  %>
        </div>
        <div class="about__parts" style="margin-left:10px">
          <p class="about__p">他の人がどんな目的で読み、<br>どんな評価をしているかが分かる！</p>
          <%= image_tag "review.png", :width => '80%', :class => 'about__image'  %>
          <p></p>
          <%= image_tag "post-show.png", :width => '80%', :class => 'about__image'  %>
        </div>
      </div>
    <h2>読書管理機能</h2>
    <div class="about__contents">
      <div class="about__parts">
        <p class="about__p">気になる本を検索して、登録する</p>
        <%= image_tag "search.png", :width => '80%', :class => 'about__image'  %>
        <p></p>
        <%= image_tag "search-result.png", :width => '80%', :class => 'about__image'  %>
      </div>
      <div class="about__parts" style="margin-left:10px">
        <p class="about__p">読みたい本と読んだ本を管理する</p>
        <%= image_tag "list.png", :width => '80%', :class => 'about__image'  %>
      </div>

    </div>

  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
  <div class="col-mx-7  col-md-offset-7 main-visual center-block ">
    <%= image_tag "bookshelf.jpg", :width => '30%', :class => 'main-visual__image'  %>
    <div class="main-visual__content">
      <h1><%= image_tag "book.png", :width => '35', :height => '35', :class => 'main-visual__icon' %>For What?</h1>
      <p class="main-visual__text">
        本を読んでいて、こんな経験はありませんか？<br>
        売れ筋の本だから買ったけど、面白くない。<br>
        この本、難しすぎる…<br>
        このサイトは、皆様の本選びをお手伝いします！<br>
      </p>
      <%= link_to "詳しく見る", about_path, class: 'btn btn-nav' %>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar" >
  <div class="container">
    <nav class='nav navbar-left'  style="padding:10px" data-turbolinks="false">
      <%= image_tag "book.png", :width => '35', :height => '35', :id => 'logo-img'  %>
      <%= link_to "For What?", root_path, id: "logo" %>
    </nav>
    <nav>
      <ul class="nav navbar-left" style="padding:12px 30px" data-turbolinks="false">
        <% if user_signed_in? %>
          <%= link_to 'マイページ', user_path(current_user), class: 'btn btn-nav' %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-nav' %>
        <% else %>
          <%= link_to 'TOP', root_path, class: 'btn btn-nav' %>
          <%= link_to 'About', about_path, class: 'btn btn-nav' %>
          <%= link_to '新規登録', new_user_registration_path, class: 'btn btn-nav' %>
          <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-nav' %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'users/profile', user: current_user %>
  </div>

  <div class="col-md-9 book">
    <%= render 'books/show', book: @book %>
    <div>
      <h2>読みたい本を登録</h2>
      <h4>読もうと思った目的や背景を教えてください。</h4>
      <p>チェックボックスを選択、もしくは自由記入欄に記入してください。</p>
      <form name="form1">
        <h4>【小説】</h4>
        <div class="radio-area">
          <input type="radio" name="why" value="好きな作家だから" onclick="clickBtn1()">
          <label>好きな作家だから</label>
          <input type="radio" name="why" value="新しい作家にチャレンジ" onclick="clickBtn1()">
          <label>新しい作家にチャレンジ</label>
          <input type="radio" name="why" value="好きなジャンルだから" onclick="clickBtn1()">
          <label>好きなジャンルだから</label><br>
          <input type="radio" name="why" value="新しいジャンルにチャレンジ" onclick="clickBtn1()">
          <label>新しいジャンルにチャレンジ</label>
          <input type="radio" name="why" value="売れ筋の本だから" onclick="clickBtn1()">
          <label>売れ筋の本だから</label>
          <input type="radio" name="why" value="学校や会社からの課題" onclick="clickBtn1()">
          <label>学校や会社からの課題</label>
        </div>
        <h4>【ビジネス書・新書・専門書】</h4>
        <h5>・内容に関する知識</h5>
        <div class="radio-area">
          <input type="radio" name="why" value="初学者" onclick="clickBtn1()">
          <label>初学者</label>
          <input type="radio" name="why" value="基礎的なことは分かる" onclick="clickBtn1()">
          <label>基礎的なことは分かる</label>
          <input type="radio" name="why" value="専門的に学んだ" onclick="clickBtn1()">
          <label>専門的に学んだ</label>
          <input type="radio" name="why" value="仕事で使っている" onclick="clickBtn1()">
          <label>仕事で使っている</label>
        </div>
        <h5>・なぜ読もうと思ったか</h5>
        <div class="radio-area">
          <input type="radio" name="why" value="学校や会社からの課題" onclick="clickBtn1()">
          <label>学校や会社からの課題</label>
          <input type="radio" name="why" value="仕事で使用" onclick="clickBtn1()">
          <label>仕事で使用</label>
          <input type="radio" name="why" value="授業で使用" onclick="clickBtn1()">
          <label>授業で使用</label>
          <input type="radio" name="why" value="興味のある内容だから" onclick="clickBtn1()">
          <label>興味のある内容だから</label>
        </div>
      </form>
        <%= form_with model: @post, url: posts_path, method: :post, local: true, html: { name: "form2"}  do |f| %>
          <h4>【自由記入】</h4>
          <%= render "layouts/flash" %>
          <%= f.text_field :reason, name: "reason", size: 100 %>
          <%= f.hidden_field :book_id, :value => @book.id %><br>
          <%= f.submit "読みたい本に登録", class: 'btn btn-link', style: 'margin-top:10px' %>
        <% end %>
    </div>
  </div>
</div>

<script>
function clickBtn1(){
  	var why = document.form1.why.value;
  	document.form2.reason.value = why;
}
</script>

app/views/posts/show.html.erb
<% provide(:title, "投稿詳細") %>
<div class="row">
  <div id="post_<%= @post.id %>">
    <div class="favorite-count col-md-3">
      <%= render 'users/profile', user: @post.user %>
    </div>
    <%= render "layouts/flash" %>
    <div class="col-md-9 book">
      <%= render 'books/show', book: @post.book %>
      <% if @post.star == nil %>
        <h2>読みたい本詳細</h2>
        <h3>【目的・背景】</h3>
        <h4><%= @post.reason %></h4>
      <% else %>
        <h2>読んだ本詳細</h2>
        <h3>【目的・背景】</h3>
        <h4>  <%= @post.reason %></h4>
        <div data-turbolinks="false">
          <h3>【評価】</h3> <div id="star" data-score="<%= @post.star %>"></div>
        </div>
        <div class="comment">
        <h3>【コメント】</h3>
        <!--<span class="comment__score">感情分析スコア  <%#= @post.score %></span>-->
        </div>
        <h4>  <%= @post.comment %></h4>
      <% end %>

      <div class="favorite-btn" style='margin:10px 0'>
        <%= render 'favorites/favorite-btn', post: @post %>
      </div>

      <% if @post.user == current_user && @post.star != nil %>
        <%= link_to "読んだ本から削除", post_path(@post), method: :delete, class: 'btn btn-del' %>
      <% elsif @post.user == current_user && @post.star == nil %>
        <%= link_to "読んだ本に登録", edit_post_path(@post), class: 'btn btn-link'%>
        <%= link_to "読みたい本から削除", post_path(@post), method: :delete, class: 'btn btn-del', style: 'margin-left:5px' %>
      <% elsif @post.user != current_user && AdminBook.where(user_id: current_user.id,book_id: @post.book.id,have_read: true).present? %>
        読んだ本に登録済み
      <% elsif @post.user != current_user && AdminBook.where(user_id: current_user.id,book_id: @post.book.id,want_read: true).present? %>
        読みたい本に登録済み
      <% elsif @post.user != current_user && AdminBook.where(user_id: current_user.id,book_id: @post.book.id).empty? %>
        <%= link_to "読みたい本に登録", new_post_path(book: @post.book), class: 'btn btn-link' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="profile">
  <div class="profile__title text-center"><i class="far fa-address-book"></i> Profile</div>
  <div class="profile__image text-center"><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></div>
  <div class="profile__name text-center"><%= user.name %></div>
  <div  class="profile__content text-center">
    <p>年齢：<%= (Date.today.strftime('%Y%m%d').to_i - user.birthday.strftime('%Y%m%d').to_i) / 10000 %>歳</p>
    <p>性別：<%= user.gender %></p>
    <p>お気に入り：<%= link_to user.favorites.count,favorite_path(user) %>件</p>
    <% if user == current_user %>
      <%= link_to "登録情報編集", edit_user_path(user.id), class:"btn btn-default" %>
    <% end %>
  </div>
  <div class="profile__book-info text-center">
    <h5><i  class="fas fa-star"></i> 読書記録</h5>
    <div>読んだ本：<%= AdminBook.where(user_id: user.id,have_read: true).count %>冊</div>
    <div>読みたい本：<%= AdminBook.where(user_id: user.id,want_read: true).count - AdminBook.where(user_id: user.id,have_read: true).count %>冊</div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "登録情報変更") %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    
    <div class="form">
      <div class="form__header text-center">
        <h4 class="form__header-title">会員情報編集</h4>
      </div>

      <div class="form__body">
        <%= form_with model: @user, url: user_path,local: true do |f| %>
          <div class="form__group has-feedback">
            <label class="sr-only">ニックネーム</label>
            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"ニックネーム"%>
            <span class="fa fa-user form-control-feedback" aria-hidden="true"></span>
          </div>
          <div class="form__group has-feedback">
            <label class="sr-only">メールアドレス</label>
            <%= f.email_field :email, class:"form-control", id:"inputEmail", placeholder:"メールアドレス"%>
            <span class="fa fa-envelope form-control-feedback" aria-hidden="true"></span>
          </div>
          <div class="form__group">
            <%= attachment_image_tag(@user, :profile_image, size: "200x200", fallback: "no_image.jpg") %>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          <div class="form__group">
            <label>生年月日</label>
            <%= f.date_select :birthday, use_month_numbers: true,start_year: 1930,
                end_year: (Time.now.year - 5), default: Date.new(1985, 1, 1) %>
          </div>
          
          <div class="form__group">
            <label>性別</label>
            <label class="radio-inline">
              <%= f.radio_button :gender, "男性", class:"radio" %>男性
            </label>
	          <label class="radio-inline">
              <%= f.radio_button :gender, "女性", class:"radio" %>女性
             </label>
          </div>
          <div class="form__group">
          <%= f.submit "変更を保存", class:"btn btn-block" %>
           </div>
        <% end %>
        <div class="form__attention">
          <p>退会は<%= link_to "こちら", unsubscribe_user_path %>から</p>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-3" data-turbolinks="false">
    <%= render 'users/profile', user: @user %>
  </div>

  <div class="col-md-9">
    <%= render "layouts/flash" %>
    <h2>本を探す</h2>
    <div class="search-form">
      <%= form_with model: @book,url: search_books_path, method: :get, local: true do |f| %>
        <%= f.select :model, options_for_select({ "タイトル" => "title", "著者" => "author" }),{},{class: 'search-form__select'}  %>
        <%= text_field :keyword, "", placeholder:'書籍タイトル、著者', size: 40, name: 'keyword', class: "search-form__box" %>
        <%= f.button :type => "submit", class: "search-form__button" do  %>
          <i class='fa fa-search'></i>
        <% end %>
      <% end %>
    </div>

    <h2>読みたい本</h2>
    <div class="table">
      <div class="table__line-title">
        <div class="table__day ">登録日</div>
        <div class="table__title">タイトル</div>
        <div class="table__author">著者名</div>
        <div class="table__link"></div>
      </div>
      <div data-turbolinks="false">
        <% @want_reads.each do |want_read| %>
        <div class="table__line">
          <div class="table__day"><%= want_read.created_at.strftime('%Y/%m/%d') %></div>
          <div class="table__title"><%= link_to want_read.book.title, want_read.book.item_url %></div>
          <div class="table__author"><%= want_read.book.author %></div>
          <div class="table__link"><%= link_to "投稿詳細", post_path(want_read.post), class: 'btn btn-link' %></div>
        </div>
        <% end %>
      </div>
    </div>
    <% unless  @want_reads.length == 0 %>
      <div class="text-center">
        <%= paginate @want_reads %>
      </div>
    <% end %>

    <h2>読んだ本</h2>
    <div class="table">
      <div class="table__line-title">
        <div class="table__day2">読了日</div>
        <div class="table__title2">タイトル</div>
        <div class="table__author2">著者名</div>
        <div class="table__star2">評価</div>
        <div class="table__link2"></div>
      </div>
      <div data-turbolinks="false">
        <% @have_reads.each_with_index do |have_read,index| %>
        <div class="table__line">
          <div class="table__day2"><%= have_read.updated_at.strftime('%Y/%m/%d') %></div>
          <div class="table__title2"><%= link_to have_read.book.title, have_read.book.item_url %></div>
          <div class="table__author2"><%= have_read.book.author %></div>
          <div class="table__star2" id="star-<%= index %>" data-score="<%= have_read.post.star %>"></div>
          <div class="table__link2"><%= link_to "投稿詳細", post_path(have_read.post), class: 'btn btn-link' %></div>
        </div>
        <% end %>
      </div>
      <% unless  @have_reads.length == 0 %>
        <div class="text-center">
          <%= paginate @have_reads %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(function () {
    for (var i=0; i<"<%= @have_reads.size %>"; i++) {
    $(`#star-${i}`).raty({
      size: 36,
      starOff: "<%= image_url('star-off.png') %>",
      starOn: "<%= image_url('star-on.png') %>",
      scoreName: "score"
    });
    };
  });
</script>

app/views/users/unsubscribe.html.erb
<% provide(:title, "退会") %>
<div class="row">
  <div class="text-center">
    <strong>本当に退会しますか？</strong>
    <div>
      退会すると会員情報登録や<br>
      これまでの履歴が閲覧できなくなります。<br>
      <br>
      退会する場合は,「退会する」をクリックしてください。
    </div>
    <%= link_to "退会しない", edit_user_path(@user), class: 'btn btn-link' %>
    <%= link_to "退会する", withdraw_user_path(@user), method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: "btn btn-del" %>
  </div>
</div>